AWSTemplateFormatVersion: "2010-09-09"
Description: Cloud resources required to deploy schoepproject.com and subroutes
Parameters:
  RepositoryOrganization:
    Type: String
    Default: joshuadschoep
  RepositoryName:
    Type: String
    Default: schoepproject-com
  PermissionsBoundary:
    Type: String
    Default: arn:aws:iam::145724753995:policy/schoepproject-general-permissions-boundary
Mappings:
  Domains:
    Prod:
      Name: www.schoep.org
      FullyResolvedName: www.schoep.org.
      S3Name: www-schoep-org-145724753995
    Redirect:
      Name: schoep.org
      FullyResolvedName: schoep.org.
      S3Name: redirect-schoep-org-145724753995
  DnsAliasTargets:
    CloudFront:
      Global: Z2FDTNDATAQYW2
    S3:
      UsEast1: Z3AQBSTGFYJSTF
  CachingPolicies:
    CachingOptimized:
      Id: 658327ea-f89d-4fab-a63d-7e88639e58f6
  CDNPriceClasses:
    USAndEurope:
      Id: PriceClass_100
  CdnSslConfig:
    Tls1.2SniOnly:
      SslVersion: TLSv1.2_2021
      SupportMethod: sni-only
Resources:
  StaticBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !FindInMap [Domains, Prod, S3Name]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
  RedirectBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !FindInMap [Domains, Redirect, S3Name]
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !FindInMap [Domains, Prod, Name]
          Protocol: https
  RedirectDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !FindInMap [Domains, Redirect, FullyResolvedName]
      Type: A
      HostedZoneId: Z04384493BYLG54AC0Z1D
      AliasTarget:
        DNSName: !Sub ${RedirectBucket}.s3-website-${AWS::Region}.amazonaws.com
        HostedZoneId: !FindInMap [DnsAliasTargets, S3, UsEast1]
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !FindInMap [Domains, Prod, FullyResolvedName]
      Type: A
      HostedZoneId: Z04384493BYLG54AC0Z1D
      AliasTarget:
        DNSName: !GetAtt CDN.DomainName
        HostedZoneId: !FindInMap [DnsAliasTargets, CloudFront, Global]
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !FindInMap [Domains, Prod, Name]
      DomainValidationOptions:
        - DomainName: !FindInMap [Domains, Prod, Name]
          HostedZoneId: Z04384493BYLG54AC0Z1D
      ValidationMethod: DNS
  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !FindInMap [Domains, Prod, Name]
        Origins:
          - DomainName: !Sub ${StaticBucket}.s3-website-${AWS::Region}.amazonaws.com
            Id: S3BucketOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          CachePolicyId: !FindInMap [CachingPolicies, CachingOptimized, Id]
          Compress: true
          # Speed up caching while developing
          DefaultTTL: 60
          TargetOriginId: S3BucketOrigin
          ViewerProtocolPolicy: "redirect-to-https"
        HttpVersion: http2and3
        PriceClass: !FindInMap [CDNPriceClasses, USAndEurope, Id]
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          MinimumProtocolVersion:
            !FindInMap [CdnSslConfig, Tls1.2SniOnly, SslVersion]
          SslSupportMethod:
            !FindInMap [CdnSslConfig, Tls1.2SniOnly, SupportMethod]
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource: !Sub "arn:${AWS::Partition}:s3:::${StaticBucket}/*"
  UploadPolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      RoleName: !Ref UploadRole
      PolicyName: schoepproject-com-site-upload
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:ListObjects
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${StaticBucket}"
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:AbortMultipartUpload
              - s3:ListMultipartUploadParts
              - s3:GetObject
              - s3:DeleteObject
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${StaticBucket}/*"
  UploadRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: schoepproject-com-site-upload
      PermissionsBoundary: !Ref PermissionsBoundary
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: arn:aws:iam::145724753995:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${RepositoryOrganization}/${RepositoryName}:ref:refs/heads/*
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
