name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      INDEX_FILE: ${{ vars.INDEX_FILE }}
      STATIC_FOLDER: ${{ vars.STATIC_FOLDER }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_CLOUDFRONT_DIST: ${{ secrets.AWS_CLOUDFRONT_DIST }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: aws-actions/configure-aws-credentials@v3
        name: Configure Deployment Credentials
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: Github-Actions-Deploy
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: actions/download-artifact@v3
        name: Download Build
        with:
          name: build
          path: build
      - run: bash ../.github/scripts/uploads3.sh
        name: Upload To S3
        working-directory: build
      - run: bash ./.github/scripts/invalidate.sh
        name: Invalidate Cache
