name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    runs-on:
      ubuntu-latest
    needs:
      build
    env:
      INDEX_FILE: ${{ variables.INDEX_FILE }}
      STATIC_FOLDER: ${{ variables.STATIC_FOLDER }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: Github-Actions-Deploy
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - run: bash ./.github/scripts/uploads3.sh
        
