name: Integration
on: pull_request
jobs:
  lint:
    uses: ./.github/workflows/eslint.yml
  test:
    uses: ./.github/workflows/jest.yml
  sast:
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write