name: Build
on: workflow_call

jobs:
  webpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install Modules
        run: npm install
      - name: Build Packages
        run: npm run build
      - name: Archive prod artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist
